// AUTO-GENERATED by scripts/build-variants.js — DO NOT EDIT.
// ============================================================================
// Dark Roast: Flash Chilled — Blink Shell Theme (iOS / iPadOS)
// Version: 5.1.0 Companion
//
// INSTALL
// -------
//   Blink imports themes from a URL, so the file has to be reachable over
//   HTTPS first (raw GitHub file or a gist both work):
//
//     1. Host this file, e.g. push the repo and use its raw URL, or run
//        `gh gist create "platforms/blink/Dark Roast Flash Chilled.js"`
//     2. In Blink: type `config` (or press ⌘,) → Appearance → Themes → New Theme
//     3. Paste the URL of the JS theme
//     4. Back in Appearance → Theme → select "Dark Roast Flash Chilled"
//
//   Blink names the theme after the file, so keep the filename intact.
//
// FORMAT
// ------
// Blink's terminal is hterm-based: a theme is a JavaScript snippet evaluated
// with the terminal instance bound to `t`. Only four preferences carry color —
// the ANSI-16 palette override, foreground, background, and cursor. Blink has
// no selection-color preference, so selection follows its own system tint.
//
// PALETTE PHILOSOPHY
// ------------------
// All five Dark Roast terminal themes (Warp, Tabby, Terminal.app, iTerm2,
// Blink) share an identical ANSI-16 palette so that ls, git diff, vim syntax,
// tmux, and every other CLI tool produce exactly the same output regardless of
// which emulator you're running.
//
// The palette is grounded in the Dark Roast design system:
//   - Background/foreground pulled directly from DR tokens (void, crema)
//   - Cursor matches the editor cursor (teal — "kinetic, live data flow"),
//     held at 65% alpha because hterm paints the cursor over the glyph rather
//     than inverting it; a solid block would swallow the character underneath
//   - ANSI normals and brights use the five DR action colors + three
//     terminal-extension colors (sage, slate, mauve) that aren't in the core
//     UI token set but sit squarely within the warm espresso aesthetic
//
// FULL COLOR REFERENCE
// --------------------
// Chrome:
//   background    #D4E1E3   void      — warm-dark deepest layer
//   foreground    #000000   crema     — primary text (15.68:1 contrast vs void)
//   cursor        #006464   teal      — kinetic, matches editor caret
//
// ANSI Normal (indices 0–7):
//   0 black       #C2D5D9   obsidian  — dark but not void; provides depth in dark bg
//   1 red         #B6011C   scarlet   — error / critical
//   2 green       #1C6402   sage      — warm fern green (terminal extension)
//   3 yellow      #7E4F01   amber     — warning / accent / CTA
//   4 blue        #015E8C   slate     — dusty steel blue (terminal extension)
//   5 magenta     #5A129D   mauve     — dried lavender (terminal extension)
//   6 cyan        #006464   teal      — live data flow / resolved
//   7 white       #000C0F   bone      — reduced-contrast light text
//
// ANSI Bright (indices 8–15):
//   8  bright black    #3B5F65   crater-deep   — comment gray / muted metadata
//   9  bright red      #B6011C   scarlet-lt    — scarlet companion-bright
//  10  bright green    #1C6700   sage-lt       — sage companion-bright
//  11  bright yellow   #725400   gold          — success / stable severity
//  12  bright blue     #015E8C   slate-lt      — slate companion-bright
//  13  bright magenta  #6605B3   mauve-lt      — mauve companion-bright
//  14  bright cyan     #006464   teal-lt       — teal brightened (noticeably lighter
//                                               than normal teal; brights should be
//                                               brighter, not identical)
//  15  bright white    #000000   crema         — full brightness
// ============================================================================

const darkRoastFlashChilled = {
  // ── ANSI normal (0–7) ─────────────────────────────────────────────────────
  black: "#C2D5D9", // obsidian — elevated floor, not as deep as void
  red: "#B6011C", // scarlet — error / critical severity
  green: "#1C6402", // sage — warm fern; git diff +lines, ls dirs
  yellow: "#7E4F01", // amber — warning / accent; DR primary CTA
  blue: "#015E8C", // slate — dusty steel; git diff header, less prompt
  magenta: "#5A129D", // mauve — dried lavender; grep matches, vim special
  cyan: "#006464", // teal — live data; matches cursor + DR teal token
  white: "#000C0F", // bone — reduced-contrast; comment-level brightness

  // ── ANSI bright (8–15) ────────────────────────────────────────────────────
  lightBlack: "#3B5F65", // crater-deep — comment gray; git log graph, tmux inactive
  lightRed: "#B6011C", // scarlet companion-bright — diff removed, error paths
  lightGreen: "#1C6700", // sage companion-bright — diff added, success paths
  lightYellow: "#725400", // gold — success / stable; git branch
  lightBlue: "#015E8C", // slate companion-bright — links, prompt path segments
  lightMagenta: "#6605B3", // mauve companion-bright — vim visual, special tokens
  lightCyan: "#006464", // teal lightened — brighter than normal teal
  lightWhite: "#000000", // crema — full brightness; bold text, headings

  // ── Chrome ────────────────────────────────────────────────────────────────
  backgroundColor: "#D4E1E3", // void — warm-dark deepest layer
  foregroundColor: "#000000", // crema — primary text, 15.68:1 contrast vs void
  cursorColor: "rgba(0, 100, 100, 0.65)", // teal at 65% — glyph stays legible under the block
};

t.prefs_.set('color-palette-overrides', [
  darkRoastFlashChilled.black,
  darkRoastFlashChilled.red,
  darkRoastFlashChilled.green,
  darkRoastFlashChilled.yellow,
  darkRoastFlashChilled.blue,
  darkRoastFlashChilled.magenta,
  darkRoastFlashChilled.cyan,
  darkRoastFlashChilled.white,
  darkRoastFlashChilled.lightBlack,
  darkRoastFlashChilled.lightRed,
  darkRoastFlashChilled.lightGreen,
  darkRoastFlashChilled.lightYellow,
  darkRoastFlashChilled.lightBlue,
  darkRoastFlashChilled.lightMagenta,
  darkRoastFlashChilled.lightCyan,
  darkRoastFlashChilled.lightWhite
]);

t.prefs_.set('foreground-color', darkRoastFlashChilled.foregroundColor);
t.prefs_.set('background-color', darkRoastFlashChilled.backgroundColor);
t.prefs_.set('cursor-color', darkRoastFlashChilled.cursorColor);
