// AUTO-GENERATED by scripts/build-variants.js — DO NOT EDIT.
// ============================================================================
// Dark Roast: Blue Mountain — Blink Shell Theme (iOS / iPadOS)
// Version: 5.1.0 Companion
//
// INSTALL
// -------
//   Blink imports themes from a URL, so the file has to be reachable over
//   HTTPS first (raw GitHub file or a gist both work):
//
//     1. Host this file, e.g. push the repo and use its raw URL, or run
//        `gh gist create "platforms/blink/Dark Roast Blue Mountain.js"`
//     2. In Blink: type `config` (or press ⌘,) → Appearance → Themes → New Theme
//     3. Paste the URL of the JS theme
//     4. Back in Appearance → Theme → select "Dark Roast Blue Mountain"
//
//   Blink names the theme after the file, so keep the filename intact.
//
// FORMAT
// ------
// Blink's terminal is hterm-based: a theme is a JavaScript snippet evaluated
// with the terminal instance bound to `t`. Only four preferences carry color —
// the ANSI-16 palette override, foreground, background, and cursor. Blink has
// no selection-color preference, so selection follows its own system tint.
//
// PALETTE PHILOSOPHY
// ------------------
// All five Dark Roast terminal themes (Warp, Tabby, Terminal.app, iTerm2,
// Blink) share an identical ANSI-16 palette so that ls, git diff, vim syntax,
// tmux, and every other CLI tool produce exactly the same output regardless of
// which emulator you're running.
//
// The palette is grounded in the Dark Roast design system:
//   - Background/foreground pulled directly from DR tokens (void, crema)
//   - Cursor matches the editor cursor (teal — "kinetic, live data flow"),
//     held at 65% alpha because hterm paints the cursor over the glyph rather
//     than inverting it; a solid block would swallow the character underneath
//   - ANSI normals and brights use the five DR action colors + three
//     terminal-extension colors (sage, slate, mauve) that aren't in the core
//     UI token set but sit squarely within the warm espresso aesthetic
//
// FULL COLOR REFERENCE
// --------------------
// Chrome:
//   background    #000b1d   void      — warm-dark deepest layer
//   foreground    #e5ecf3   crema     — primary text (16.54:1 contrast vs void)
//   cursor        #00b5b5   teal      — kinetic, matches editor caret
//
// ANSI Normal (indices 0–7):
//   0 black       #001228   obsidian  — dark but not void; provides depth in dark bg
//   1 red         #f86572   scarlet   — error / critical
//   2 green       #60a563   sage      — warm fern green (terminal extension)
//   3 yellow      #ef912d   amber     — warning / accent / CTA
//   4 blue        #49accf   slate     — dusty steel blue (terminal extension)
//   5 magenta     #b181e5   mauve     — dried lavender (terminal extension)
//   6 cyan        #00b5b5   teal      — live data flow / resolved
//   7 white       #c3cfdc   bone      — reduced-contrast light text
//
// ANSI Bright (indices 8–15):
//   8  bright black    #8797a9   crater-deep   — comment gray / muted metadata
//   9  bright red      #f55e6c   scarlet-lt    — scarlet companion-bright
//  10  bright green    #6dba70   sage-lt       — sage companion-bright
//  11  bright yellow   #ebaa1f   gold          — success / stable severity
//  12  bright blue     #49c1ea   slate-lt      — slate companion-bright
//  13  bright magenta  #bd87f6   mauve-lt      — mauve companion-bright
//  14  bright cyan     #00caca   teal-lt       — teal brightened (noticeably lighter
//                                               than normal teal; brights should be
//                                               brighter, not identical)
//  15  bright white    #e5ecf3   crema         — full brightness
// ============================================================================

const darkRoastBlueMountain = {
  // ── ANSI normal (0–7) ─────────────────────────────────────────────────────
  black: "#001228", // obsidian — elevated floor, not as deep as void
  red: "#f86572", // scarlet — error / critical severity
  green: "#60a563", // sage — warm fern; git diff +lines, ls dirs
  yellow: "#ef912d", // amber — warning / accent; DR primary CTA
  blue: "#49accf", // slate — dusty steel; git diff header, less prompt
  magenta: "#b181e5", // mauve — dried lavender; grep matches, vim special
  cyan: "#00b5b5", // teal — live data; matches cursor + DR teal token
  white: "#c3cfdc", // bone — reduced-contrast; comment-level brightness

  // ── ANSI bright (8–15) ────────────────────────────────────────────────────
  lightBlack: "#8797a9", // crater-deep — comment gray; git log graph, tmux inactive
  lightRed: "#f55e6c", // scarlet companion-bright — diff removed, error paths
  lightGreen: "#6dba70", // sage companion-bright — diff added, success paths
  lightYellow: "#ebaa1f", // gold — success / stable; git branch
  lightBlue: "#49c1ea", // slate companion-bright — links, prompt path segments
  lightMagenta: "#bd87f6", // mauve companion-bright — vim visual, special tokens
  lightCyan: "#00caca", // teal lightened — brighter than normal teal
  lightWhite: "#e5ecf3", // crema — full brightness; bold text, headings

  // ── Chrome ────────────────────────────────────────────────────────────────
  backgroundColor: "#000b1d", // void — warm-dark deepest layer
  foregroundColor: "#e5ecf3", // crema — primary text, 16.54:1 contrast vs void
  cursorColor: "rgba(0, 181, 181, 0.65)", // teal at 65% — glyph stays legible under the block
};

t.prefs_.set('color-palette-overrides', [
  darkRoastBlueMountain.black,
  darkRoastBlueMountain.red,
  darkRoastBlueMountain.green,
  darkRoastBlueMountain.yellow,
  darkRoastBlueMountain.blue,
  darkRoastBlueMountain.magenta,
  darkRoastBlueMountain.cyan,
  darkRoastBlueMountain.white,
  darkRoastBlueMountain.lightBlack,
  darkRoastBlueMountain.lightRed,
  darkRoastBlueMountain.lightGreen,
  darkRoastBlueMountain.lightYellow,
  darkRoastBlueMountain.lightBlue,
  darkRoastBlueMountain.lightMagenta,
  darkRoastBlueMountain.lightCyan,
  darkRoastBlueMountain.lightWhite
]);

t.prefs_.set('foreground-color', darkRoastBlueMountain.foregroundColor);
t.prefs_.set('background-color', darkRoastBlueMountain.backgroundColor);
t.prefs_.set('cursor-color', darkRoastBlueMountain.cursorColor);
