// AUTO-GENERATED by scripts/build-variants.js — DO NOT EDIT.
// ============================================================================
// Dark Roast: Velvet Noir — Blink Shell Theme (iOS / iPadOS)
// Version: 5.1.0 Companion
//
// INSTALL
// -------
//   Blink imports themes from a URL, so the file has to be reachable over
//   HTTPS first (raw GitHub file or a gist both work):
//
//     1. Host this file, e.g. push the repo and use its raw URL, or run
//        `gh gist create "platforms/blink/Dark Roast Velvet Noir.js"`
//     2. In Blink: type `config` (or press ⌘,) → Appearance → Themes → New Theme
//     3. Paste the URL of the JS theme
//     4. Back in Appearance → Theme → select "Dark Roast Velvet Noir"
//
//   Blink names the theme after the file, so keep the filename intact.
//
// FORMAT
// ------
// Blink's terminal is hterm-based: a theme is a JavaScript snippet evaluated
// with the terminal instance bound to `t`. Only four preferences carry color —
// the ANSI-16 palette override, foreground, background, and cursor. Blink has
// no selection-color preference, so selection follows its own system tint.
//
// PALETTE PHILOSOPHY
// ------------------
// All five Dark Roast terminal themes (Warp, Tabby, Terminal.app, iTerm2,
// Blink) share an identical ANSI-16 palette so that ls, git diff, vim syntax,
// tmux, and every other CLI tool produce exactly the same output regardless of
// which emulator you're running.
//
// The palette is grounded in the Dark Roast design system:
//   - Background/foreground pulled directly from DR tokens (void, crema)
//   - Cursor matches the editor cursor (teal — "kinetic, live data flow"),
//     held at 65% alpha because hterm paints the cursor over the glyph rather
//     than inverting it; a solid block would swallow the character underneath
//   - ANSI normals and brights use the five DR action colors + three
//     terminal-extension colors (sage, slate, mauve) that aren't in the core
//     UI token set but sit squarely within the warm espresso aesthetic
//
// FULL COLOR REFERENCE
// --------------------
// Chrome:
//   background    #14030C   void      — warm-dark deepest layer
//   foreground    #F6E4DA   crema     — primary text (16.25:1 contrast vs void)
//   cursor        #36AFAB   teal      — kinetic, matches editor caret
//
// ANSI Normal (indices 0–7):
//   0 black       #1F0514   obsidian  — dark but not void; provides depth in dark bg
//   1 red         #D4445E   scarlet   — error / critical
//   2 green       #51A460   sage      — warm fern green (terminal extension)
//   3 yellow      #E28233   amber     — warning / accent / CTA
//   4 blue        #6486B9   slate     — dusty steel blue (terminal extension)
//   5 magenta     #C85BA0   mauve     — dried lavender (terminal extension)
//   6 cyan        #36AFAB   teal      — live data flow / resolved
//   7 white       #E3CAC0   bone      — reduced-contrast light text
//
// ANSI Bright (indices 8–15):
//   8  bright black    #A88594   crater-deep   — comment gray / muted metadata
//   9  bright red      #EC6175   scarlet-lt    — scarlet companion-bright
//  10  bright green    #70BB7C   sage-lt       — sage companion-bright
//  11  bright yellow   #E8A72D   gold          — success / stable severity
//  12  bright blue     #7B9ED2   slate-lt      — slate companion-bright
//  13  bright magenta  #E076B7   mauve-lt      — mauve companion-bright
//  14  bright cyan     #59CAC5   teal-lt       — teal brightened (noticeably lighter
//                                               than normal teal; brights should be
//                                               brighter, not identical)
//  15  bright white    #F6E4DA   crema         — full brightness
// ============================================================================

const darkRoastVelvetNoir = {
  // ── ANSI normal (0–7) ─────────────────────────────────────────────────────
  black: "#1F0514", // obsidian — elevated floor, not as deep as void
  red: "#D4445E", // scarlet — error / critical severity
  green: "#51A460", // sage — warm fern; git diff +lines, ls dirs
  yellow: "#E28233", // amber — warning / accent; DR primary CTA
  blue: "#6486B9", // slate — dusty steel; git diff header, less prompt
  magenta: "#C85BA0", // mauve — dried lavender; grep matches, vim special
  cyan: "#36AFAB", // teal — live data; matches cursor + DR teal token
  white: "#E3CAC0", // bone — reduced-contrast; comment-level brightness

  // ── ANSI bright (8–15) ────────────────────────────────────────────────────
  lightBlack: "#A88594", // crater-deep — comment gray; git log graph, tmux inactive
  lightRed: "#EC6175", // scarlet companion-bright — diff removed, error paths
  lightGreen: "#70BB7C", // sage companion-bright — diff added, success paths
  lightYellow: "#E8A72D", // gold — success / stable; git branch
  lightBlue: "#7B9ED2", // slate companion-bright — links, prompt path segments
  lightMagenta: "#E076B7", // mauve companion-bright — vim visual, special tokens
  lightCyan: "#59CAC5", // teal lightened — brighter than normal teal
  lightWhite: "#F6E4DA", // crema — full brightness; bold text, headings

  // ── Chrome ────────────────────────────────────────────────────────────────
  backgroundColor: "#14030C", // void — warm-dark deepest layer
  foregroundColor: "#F6E4DA", // crema — primary text, 16.25:1 contrast vs void
  cursorColor: "rgba(54, 175, 171, 0.65)", // teal at 65% — glyph stays legible under the block
};

t.prefs_.set('color-palette-overrides', [
  darkRoastVelvetNoir.black,
  darkRoastVelvetNoir.red,
  darkRoastVelvetNoir.green,
  darkRoastVelvetNoir.yellow,
  darkRoastVelvetNoir.blue,
  darkRoastVelvetNoir.magenta,
  darkRoastVelvetNoir.cyan,
  darkRoastVelvetNoir.white,
  darkRoastVelvetNoir.lightBlack,
  darkRoastVelvetNoir.lightRed,
  darkRoastVelvetNoir.lightGreen,
  darkRoastVelvetNoir.lightYellow,
  darkRoastVelvetNoir.lightBlue,
  darkRoastVelvetNoir.lightMagenta,
  darkRoastVelvetNoir.lightCyan,
  darkRoastVelvetNoir.lightWhite
]);

t.prefs_.set('foreground-color', darkRoastVelvetNoir.foregroundColor);
t.prefs_.set('background-color', darkRoastVelvetNoir.backgroundColor);
t.prefs_.set('cursor-color', darkRoastVelvetNoir.cursorColor);
