// AUTO-GENERATED by scripts/build-variants.js — DO NOT EDIT.
// ============================================================================
// Dark Roast: House Blend — Blink Shell Theme (iOS / iPadOS)
// Version: 5.1.0 Companion
//
// INSTALL
// -------
//   Blink imports themes from a URL, so the file has to be reachable over
//   HTTPS first (raw GitHub file or a gist both work):
//
//     1. Host this file, e.g. push the repo and use its raw URL, or run
//        `gh gist create "platforms/blink/Dark Roast House Blend.js"`
//     2. In Blink: type `config` (or press ⌘,) → Appearance → Themes → New Theme
//     3. Paste the URL of the JS theme
//     4. Back in Appearance → Theme → select "Dark Roast House Blend"
//
//   Blink names the theme after the file, so keep the filename intact.
//
// FORMAT
// ------
// Blink's terminal is hterm-based: a theme is a JavaScript snippet evaluated
// with the terminal instance bound to `t`. Only four preferences carry color —
// the ANSI-16 palette override, foreground, background, and cursor. Blink has
// no selection-color preference, so selection follows its own system tint.
//
// PALETTE PHILOSOPHY
// ------------------
// All five Dark Roast terminal themes (Warp, Tabby, Terminal.app, iTerm2,
// Blink) share an identical ANSI-16 palette so that ls, git diff, vim syntax,
// tmux, and every other CLI tool produce exactly the same output regardless of
// which emulator you're running.
//
// The palette is grounded in the Dark Roast design system:
//   - Background/foreground pulled directly from DR tokens (void, crema)
//   - Cursor matches the editor cursor (teal — "kinetic, live data flow"),
//     held at 65% alpha because hterm paints the cursor over the glyph rather
//     than inverting it; a solid block would swallow the character underneath
//   - ANSI normals and brights use the five DR action colors + three
//     terminal-extension colors (sage, slate, mauve) that aren't in the core
//     UI token set but sit squarely within the warm espresso aesthetic
//
// FULL COLOR REFERENCE
// --------------------
// Chrome:
//   background    #241810   void      — warm-dark deepest layer
//   foreground    #FFF8F0   crema     — primary text (16.43:1 contrast vs void)
//   cursor        #2CB9AA   teal      — kinetic, matches editor caret
//
// ANSI Normal (indices 0–7):
//   0 black       #2B1D14   obsidian  — dark but not void; provides depth in dark bg
//   1 red         #FE8175   scarlet   — error / critical
//   2 green       #79B56C   sage      — warm fern green (terminal extension)
//   3 yellow      #E9922E   amber     — warning / accent / CTA
//   4 blue        #6AACE2   slate     — dusty steel blue (terminal extension)
//   5 magenta     #D28DE2   mauve     — dried lavender (terminal extension)
//   6 cyan        #2CB9AA   teal      — live data flow / resolved
//   7 white       #E9DCCF   bone      — reduced-contrast light text
//
// ANSI Bright (indices 8–15):
//   8  bright black    #BCA18A   crater-deep   — comment gray / muted metadata
//   9  bright red      #FF9286   scarlet-lt    — scarlet companion-bright
//  10  bright green    #98D083   sage-lt       — sage companion-bright
//  11  bright yellow   #D0A200   gold          — success / stable severity
//  12  bright blue     #68C7F4   slate-lt      — slate companion-bright
//  13  bright magenta  #E792DF   mauve-lt      — mauve companion-bright
//  14  bright cyan     #72D8CA   teal-lt       — teal brightened (noticeably lighter
//                                               than normal teal; brights should be
//                                               brighter, not identical)
//  15  bright white    #FFF8F0   crema         — full brightness
// ============================================================================

const darkRoastHouseBlend = {
  // ── ANSI normal (0–7) ─────────────────────────────────────────────────────
  black: "#2B1D14", // obsidian — elevated floor, not as deep as void
  red: "#FE8175", // scarlet — error / critical severity
  green: "#79B56C", // sage — warm fern; git diff +lines, ls dirs
  yellow: "#E9922E", // amber — warning / accent; DR primary CTA
  blue: "#6AACE2", // slate — dusty steel; git diff header, less prompt
  magenta: "#D28DE2", // mauve — dried lavender; grep matches, vim special
  cyan: "#2CB9AA", // teal — live data; matches cursor + DR teal token
  white: "#E9DCCF", // bone — reduced-contrast; comment-level brightness

  // ── ANSI bright (8–15) ────────────────────────────────────────────────────
  lightBlack: "#BCA18A", // crater-deep — comment gray; git log graph, tmux inactive
  lightRed: "#FF9286", // scarlet companion-bright — diff removed, error paths
  lightGreen: "#98D083", // sage companion-bright — diff added, success paths
  lightYellow: "#D0A200", // gold — success / stable; git branch
  lightBlue: "#68C7F4", // slate companion-bright — links, prompt path segments
  lightMagenta: "#E792DF", // mauve companion-bright — vim visual, special tokens
  lightCyan: "#72D8CA", // teal lightened — brighter than normal teal
  lightWhite: "#FFF8F0", // crema — full brightness; bold text, headings

  // ── Chrome ────────────────────────────────────────────────────────────────
  backgroundColor: "#241810", // void — warm-dark deepest layer
  foregroundColor: "#FFF8F0", // crema — primary text, 16.43:1 contrast vs void
  cursorColor: "rgba(44, 185, 170, 0.65)", // teal at 65% — glyph stays legible under the block
};

t.prefs_.set('color-palette-overrides', [
  darkRoastHouseBlend.black,
  darkRoastHouseBlend.red,
  darkRoastHouseBlend.green,
  darkRoastHouseBlend.yellow,
  darkRoastHouseBlend.blue,
  darkRoastHouseBlend.magenta,
  darkRoastHouseBlend.cyan,
  darkRoastHouseBlend.white,
  darkRoastHouseBlend.lightBlack,
  darkRoastHouseBlend.lightRed,
  darkRoastHouseBlend.lightGreen,
  darkRoastHouseBlend.lightYellow,
  darkRoastHouseBlend.lightBlue,
  darkRoastHouseBlend.lightMagenta,
  darkRoastHouseBlend.lightCyan,
  darkRoastHouseBlend.lightWhite
]);

t.prefs_.set('foreground-color', darkRoastHouseBlend.foregroundColor);
t.prefs_.set('background-color', darkRoastHouseBlend.backgroundColor);
t.prefs_.set('cursor-color', darkRoastHouseBlend.cursorColor);
