// AUTO-GENERATED by scripts/build-variants.js — DO NOT EDIT.
// ============================================================================
// Dark Roast: Copper Roast — Blink Shell Theme (iOS / iPadOS)
// Version: 5.1.0 Companion
//
// INSTALL
// -------
//   Blink imports themes from a URL, so the file has to be reachable over
//   HTTPS first (raw GitHub file or a gist both work):
//
//     1. Host this file, e.g. push the repo and use its raw URL, or run
//        `gh gist create "platforms/blink/Dark Roast Copper Roast.js"`
//     2. In Blink: type `config` (or press ⌘,) → Appearance → Themes → New Theme
//     3. Paste the URL of the JS theme
//     4. Back in Appearance → Theme → select "Dark Roast Copper Roast"
//
//   Blink names the theme after the file, so keep the filename intact.
//
// FORMAT
// ------
// Blink's terminal is hterm-based: a theme is a JavaScript snippet evaluated
// with the terminal instance bound to `t`. Only four preferences carry color —
// the ANSI-16 palette override, foreground, background, and cursor. Blink has
// no selection-color preference, so selection follows its own system tint.
//
// PALETTE PHILOSOPHY
// ------------------
// All five Dark Roast terminal themes (Warp, Tabby, Terminal.app, iTerm2,
// Blink) share an identical ANSI-16 palette so that ls, git diff, vim syntax,
// tmux, and every other CLI tool produce exactly the same output regardless of
// which emulator you're running.
//
// The palette is grounded in the Dark Roast design system:
//   - Background/foreground pulled directly from DR tokens (void, crema)
//   - Cursor matches the editor cursor (teal — "kinetic, live data flow"),
//     held at 65% alpha because hterm paints the cursor over the glyph rather
//     than inverting it; a solid block would swallow the character underneath
//   - ANSI normals and brights use the five DR action colors + three
//     terminal-extension colors (sage, slate, mauve) that aren't in the core
//     UI token set but sit squarely within the warm espresso aesthetic
//
// FULL COLOR REFERENCE
// --------------------
// Chrome:
//   background    #34251C   void      — warm-dark deepest layer
//   foreground    #FFF9F4   crema     — primary text (14.09:1 contrast vs void)
//   cursor        #24C6B6   teal      — kinetic, matches editor caret
//
// ANSI Normal (indices 0–7):
//   0 black       #3A2A20   obsidian  — dark but not void; provides depth in dark bg
//   1 red         #FF7D70   scarlet   — error / critical
//   2 green       #7DC45F   sage      — warm fern green (terminal extension)
//   3 yellow      #F5A33A   amber     — warning / accent / CTA
//   4 blue        #5DB4E8   slate     — dusty steel blue (terminal extension)
//   5 magenta     #DB86D0   mauve     — dried lavender (terminal extension)
//   6 cyan        #24C6B6   teal      — live data flow / resolved
//   7 white       #F3E7DD   bone      — reduced-contrast light text
//
// ANSI Bright (indices 8–15):
//   8  bright black    #C4A78E   crater-deep   — comment gray / muted metadata
//   9  bright red      #FF9184   scarlet-lt    — scarlet companion-bright
//  10  bright green    #A3DD7B   sage-lt       — sage companion-bright
//  11  bright yellow   #E4B20B   gold          — success / stable severity
//  12  bright blue     #68D0F8   slate-lt      — slate companion-bright
//  13  bright magenta  #EC94E0   mauve-lt      — mauve companion-bright
//  14  bright cyan     #5FE0D1   teal-lt       — teal brightened (noticeably lighter
//                                               than normal teal; brights should be
//                                               brighter, not identical)
//  15  bright white    #FFF9F4   crema         — full brightness
// ============================================================================

const darkRoastCopperRoast = {
  // ── ANSI normal (0–7) ─────────────────────────────────────────────────────
  black: "#3A2A20", // obsidian — elevated floor, not as deep as void
  red: "#FF7D70", // scarlet — error / critical severity
  green: "#7DC45F", // sage — warm fern; git diff +lines, ls dirs
  yellow: "#F5A33A", // amber — warning / accent; DR primary CTA
  blue: "#5DB4E8", // slate — dusty steel; git diff header, less prompt
  magenta: "#DB86D0", // mauve — dried lavender; grep matches, vim special
  cyan: "#24C6B6", // teal — live data; matches cursor + DR teal token
  white: "#F3E7DD", // bone — reduced-contrast; comment-level brightness

  // ── ANSI bright (8–15) ────────────────────────────────────────────────────
  lightBlack: "#C4A78E", // crater-deep — comment gray; git log graph, tmux inactive
  lightRed: "#FF9184", // scarlet companion-bright — diff removed, error paths
  lightGreen: "#A3DD7B", // sage companion-bright — diff added, success paths
  lightYellow: "#E4B20B", // gold — success / stable; git branch
  lightBlue: "#68D0F8", // slate companion-bright — links, prompt path segments
  lightMagenta: "#EC94E0", // mauve companion-bright — vim visual, special tokens
  lightCyan: "#5FE0D1", // teal lightened — brighter than normal teal
  lightWhite: "#FFF9F4", // crema — full brightness; bold text, headings

  // ── Chrome ────────────────────────────────────────────────────────────────
  backgroundColor: "#34251C", // void — warm-dark deepest layer
  foregroundColor: "#FFF9F4", // crema — primary text, 14.09:1 contrast vs void
  cursorColor: "rgba(36, 198, 182, 0.65)", // teal at 65% — glyph stays legible under the block
};

t.prefs_.set('color-palette-overrides', [
  darkRoastCopperRoast.black,
  darkRoastCopperRoast.red,
  darkRoastCopperRoast.green,
  darkRoastCopperRoast.yellow,
  darkRoastCopperRoast.blue,
  darkRoastCopperRoast.magenta,
  darkRoastCopperRoast.cyan,
  darkRoastCopperRoast.white,
  darkRoastCopperRoast.lightBlack,
  darkRoastCopperRoast.lightRed,
  darkRoastCopperRoast.lightGreen,
  darkRoastCopperRoast.lightYellow,
  darkRoastCopperRoast.lightBlue,
  darkRoastCopperRoast.lightMagenta,
  darkRoastCopperRoast.lightCyan,
  darkRoastCopperRoast.lightWhite
]);

t.prefs_.set('foreground-color', darkRoastCopperRoast.foregroundColor);
t.prefs_.set('background-color', darkRoastCopperRoast.backgroundColor);
t.prefs_.set('cursor-color', darkRoastCopperRoast.cursorColor);
