// AUTO-GENERATED by scripts/build-variants.js — DO NOT EDIT.
// ============================================================================
// Dark Roast: Cascara — Blink Shell Theme (iOS / iPadOS)
// Version: 5.1.0 Companion
//
// INSTALL
// -------
//   Blink imports themes from a URL, so the file has to be reachable over
//   HTTPS first (raw GitHub file or a gist both work):
//
//     1. Host this file, e.g. push the repo and use its raw URL, or run
//        `gh gist create "platforms/blink/Dark Roast Cascara.js"`
//     2. In Blink: type `config` (or press ⌘,) → Appearance → Themes → New Theme
//     3. Paste the URL of the JS theme
//     4. Back in Appearance → Theme → select "Dark Roast Cascara"
//
//   Blink names the theme after the file, so keep the filename intact.
//
// FORMAT
// ------
// Blink's terminal is hterm-based: a theme is a JavaScript snippet evaluated
// with the terminal instance bound to `t`. Only four preferences carry color —
// the ANSI-16 palette override, foreground, background, and cursor. Blink has
// no selection-color preference, so selection follows its own system tint.
//
// PALETTE PHILOSOPHY
// ------------------
// All five Dark Roast terminal themes (Warp, Tabby, Terminal.app, iTerm2,
// Blink) share an identical ANSI-16 palette so that ls, git diff, vim syntax,
// tmux, and every other CLI tool produce exactly the same output regardless of
// which emulator you're running.
//
// The palette is grounded in the Dark Roast design system:
//   - Background/foreground pulled directly from DR tokens (void, crema)
//   - Cursor matches the editor cursor (teal — "kinetic, live data flow"),
//     held at 65% alpha because hterm paints the cursor over the glyph rather
//     than inverting it; a solid block would swallow the character underneath
//   - ANSI normals and brights use the five DR action colors + three
//     terminal-extension colors (sage, slate, mauve) that aren't in the core
//     UI token set but sit squarely within the warm espresso aesthetic
//
// FULL COLOR REFERENCE
// --------------------
// Chrome:
//   background    #E5DBDA   void      — warm-dark deepest layer
//   foreground    #010000   crema     — primary text (15.46:1 contrast vs void)
//   cursor        #004444   teal      — kinetic, matches editor caret
//
// ANSI Normal (indices 0–7):
//   0 black       #DCCDCB   obsidian  — dark but not void; provides depth in dark bg
//   1 red         #940015   scarlet   — error / critical
//   2 green       #0D3E00   sage      — warm fern green (terminal extension)
//   3 yellow      #492B00   amber     — warning / accent / CTA
//   4 blue        #003F60   slate     — dusty steel blue (terminal extension)
//   5 magenta     #491A7C   mauve     — dried lavender (terminal extension)
//   6 cyan        #004444   teal      — live data flow / resolved
//   7 white       #130504   bone      — reduced-contrast light text
//
// ANSI Bright (indices 8–15):
//   8  bright black    #846A68   crater-deep   — comment gray / muted metadata
//   9  bright red      #8A0012   scarlet-lt    — scarlet companion-bright
//  10  bright green    #093300   sage-lt       — sage companion-bright
//  11  bright yellow   #2D1F00   gold          — success / stable severity
//  12  bright blue     #00314C   slate-lt      — slate companion-bright
//  13  bright magenta  #3D006F   mauve-lt      — mauve companion-bright
//  14  bright cyan     #003636   teal-lt       — teal brightened (noticeably lighter
//                                               than normal teal; brights should be
//                                               brighter, not identical)
//  15  bright white    #010000   crema         — full brightness
// ============================================================================

const darkRoastCascara = {
  // ── ANSI normal (0–7) ─────────────────────────────────────────────────────
  black: "#DCCDCB", // obsidian — elevated floor, not as deep as void
  red: "#940015", // scarlet — error / critical severity
  green: "#0D3E00", // sage — warm fern; git diff +lines, ls dirs
  yellow: "#492B00", // amber — warning / accent; DR primary CTA
  blue: "#003F60", // slate — dusty steel; git diff header, less prompt
  magenta: "#491A7C", // mauve — dried lavender; grep matches, vim special
  cyan: "#004444", // teal — live data; matches cursor + DR teal token
  white: "#130504", // bone — reduced-contrast; comment-level brightness

  // ── ANSI bright (8–15) ────────────────────────────────────────────────────
  lightBlack: "#846A68", // crater-deep — comment gray; git log graph, tmux inactive
  lightRed: "#8A0012", // scarlet companion-bright — diff removed, error paths
  lightGreen: "#093300", // sage companion-bright — diff added, success paths
  lightYellow: "#2D1F00", // gold — success / stable; git branch
  lightBlue: "#00314C", // slate companion-bright — links, prompt path segments
  lightMagenta: "#3D006F", // mauve companion-bright — vim visual, special tokens
  lightCyan: "#003636", // teal lightened — brighter than normal teal
  lightWhite: "#010000", // crema — full brightness; bold text, headings

  // ── Chrome ────────────────────────────────────────────────────────────────
  backgroundColor: "#E5DBDA", // void — warm-dark deepest layer
  foregroundColor: "#010000", // crema — primary text, 15.46:1 contrast vs void
  cursorColor: "rgba(0, 68, 68, 0.65)", // teal at 65% — glyph stays legible under the block
};

t.prefs_.set('color-palette-overrides', [
  darkRoastCascara.black,
  darkRoastCascara.red,
  darkRoastCascara.green,
  darkRoastCascara.yellow,
  darkRoastCascara.blue,
  darkRoastCascara.magenta,
  darkRoastCascara.cyan,
  darkRoastCascara.white,
  darkRoastCascara.lightBlack,
  darkRoastCascara.lightRed,
  darkRoastCascara.lightGreen,
  darkRoastCascara.lightYellow,
  darkRoastCascara.lightBlue,
  darkRoastCascara.lightMagenta,
  darkRoastCascara.lightCyan,
  darkRoastCascara.lightWhite
]);

t.prefs_.set('foreground-color', darkRoastCascara.foregroundColor);
t.prefs_.set('background-color', darkRoastCascara.backgroundColor);
t.prefs_.set('cursor-color', darkRoastCascara.cursorColor);
