// AUTO-GENERATED by scripts/build-variants.js — DO NOT EDIT.
// ============================================================================
// Dark Roast: Velvet — Blink Shell Theme (iOS / iPadOS)
// Version: 5.1.0 Companion
//
// INSTALL
// -------
//   Blink imports themes from a URL, so the file has to be reachable over
//   HTTPS first (raw GitHub file or a gist both work):
//
//     1. Host this file, e.g. push the repo and use its raw URL, or run
//        `gh gist create "platforms/blink/Dark Roast Velvet.js"`
//     2. In Blink: type `config` (or press ⌘,) → Appearance → Themes → New Theme
//     3. Paste the URL of the JS theme
//     4. Back in Appearance → Theme → select "Dark Roast Velvet"
//
//   Blink names the theme after the file, so keep the filename intact.
//
// FORMAT
// ------
// Blink's terminal is hterm-based: a theme is a JavaScript snippet evaluated
// with the terminal instance bound to `t`. Only four preferences carry color —
// the ANSI-16 palette override, foreground, background, and cursor. Blink has
// no selection-color preference, so selection follows its own system tint.
//
// PALETTE PHILOSOPHY
// ------------------
// All five Dark Roast terminal themes (Warp, Tabby, Terminal.app, iTerm2,
// Blink) share an identical ANSI-16 palette so that ls, git diff, vim syntax,
// tmux, and every other CLI tool produce exactly the same output regardless of
// which emulator you're running.
//
// The palette is grounded in the Dark Roast design system:
//   - Background/foreground pulled directly from DR tokens (void, crema)
//   - Cursor matches the editor cursor (teal — "kinetic, live data flow"),
//     held at 65% alpha because hterm paints the cursor over the glyph rather
//     than inverting it; a solid block would swallow the character underneath
//   - ANSI normals and brights use the five DR action colors + three
//     terminal-extension colors (sage, slate, mauve) that aren't in the core
//     UI token set but sit squarely within the warm espresso aesthetic
//
// FULL COLOR REFERENCE
// --------------------
// Chrome:
//   background    #190605   void      — warm-dark deepest layer
//   foreground    #F7EADE   crema     — primary text (16.62:1 contrast vs void)
//   cursor        #42B3A8   teal      — kinetic, matches editor caret
//
// ANSI Normal (indices 0–7):
//   0 black       #240A09   obsidian  — dark but not void; provides depth in dark bg
//   1 red         #D4494E   scarlet   — error / critical
//   2 green       #60A659   sage      — warm fern green (terminal extension)
//   3 yellow      #E18826   amber     — warning / accent / CTA
//   4 blue        #608BB7   slate     — dusty steel blue (terminal extension)
//   5 magenta     #BC60AD   mauve     — dried lavender (terminal extension)
//   6 cyan        #42B3A8   teal      — live data flow / resolved
//   7 white       #E4D1C2   bone      — reduced-contrast light text
//
// ANSI Bright (indices 8–15):
//   8  bright black    #AC8981   crater-deep   — comment gray / muted metadata
//   9  bright red      #ED6667   scarlet-lt    — scarlet companion-bright
//  10  bright green    #7EBE77   sage-lt       — sage companion-bright
//  11  bright yellow   #E4AE28   gold          — success / stable severity
//  12  bright blue     #77A3D0   slate-lt      — slate companion-bright
//  13  bright magenta  #D47AC4   mauve-lt      — mauve companion-bright
//  14  bright cyan     #63CDC1   teal-lt       — teal brightened (noticeably lighter
//                                               than normal teal; brights should be
//                                               brighter, not identical)
//  15  bright white    #F7EADE   crema         — full brightness
// ============================================================================

const darkRoastVelvet = {
  // ── ANSI normal (0–7) ─────────────────────────────────────────────────────
  black: "#240A09", // obsidian — elevated floor, not as deep as void
  red: "#D4494E", // scarlet — error / critical severity
  green: "#60A659", // sage — warm fern; git diff +lines, ls dirs
  yellow: "#E18826", // amber — warning / accent; DR primary CTA
  blue: "#608BB7", // slate — dusty steel; git diff header, less prompt
  magenta: "#BC60AD", // mauve — dried lavender; grep matches, vim special
  cyan: "#42B3A8", // teal — live data; matches cursor + DR teal token
  white: "#E4D1C2", // bone — reduced-contrast; comment-level brightness

  // ── ANSI bright (8–15) ────────────────────────────────────────────────────
  lightBlack: "#AC8981", // crater-deep — comment gray; git log graph, tmux inactive
  lightRed: "#ED6667", // scarlet companion-bright — diff removed, error paths
  lightGreen: "#7EBE77", // sage companion-bright — diff added, success paths
  lightYellow: "#E4AE28", // gold — success / stable; git branch
  lightBlue: "#77A3D0", // slate companion-bright — links, prompt path segments
  lightMagenta: "#D47AC4", // mauve companion-bright — vim visual, special tokens
  lightCyan: "#63CDC1", // teal lightened — brighter than normal teal
  lightWhite: "#F7EADE", // crema — full brightness; bold text, headings

  // ── Chrome ────────────────────────────────────────────────────────────────
  backgroundColor: "#190605", // void — warm-dark deepest layer
  foregroundColor: "#F7EADE", // crema — primary text, 16.62:1 contrast vs void
  cursorColor: "rgba(66, 179, 168, 0.65)", // teal at 65% — glyph stays legible under the block
};

t.prefs_.set('color-palette-overrides', [
  darkRoastVelvet.black,
  darkRoastVelvet.red,
  darkRoastVelvet.green,
  darkRoastVelvet.yellow,
  darkRoastVelvet.blue,
  darkRoastVelvet.magenta,
  darkRoastVelvet.cyan,
  darkRoastVelvet.white,
  darkRoastVelvet.lightBlack,
  darkRoastVelvet.lightRed,
  darkRoastVelvet.lightGreen,
  darkRoastVelvet.lightYellow,
  darkRoastVelvet.lightBlue,
  darkRoastVelvet.lightMagenta,
  darkRoastVelvet.lightCyan,
  darkRoastVelvet.lightWhite
]);

t.prefs_.set('foreground-color', darkRoastVelvet.foregroundColor);
t.prefs_.set('background-color', darkRoastVelvet.backgroundColor);
t.prefs_.set('cursor-color', darkRoastVelvet.cursorColor);
