// AUTO-GENERATED by scripts/build-variants.js — DO NOT EDIT.
import SwiftUI

/// Additive, side-by-side Dark Roast palettes. The legacy DarkRoast API remains unchanged.
public enum DarkRoastThemeVariant: String, CaseIterable, Identifiable {
    case blackLabel = "black-label"
    case houseBlend = "house-blend"
    case copperRoast = "copper-roast"
    case coldBrew = "cold-brew"
    case nitro = "nitro"
    case flashChilled = "flash-chilled"
    case cascara = "cascara"

    public var id: String { rawValue }

    public var palette: DarkRoastPalette {
        switch self {
        case .blackLabel:
            return DarkRoastPalette(
            void_: drColor(0x120C06),
            obsidian: drColor(0x160E08),
            darkCacao: drColor(0x1E140E),
            espresso: drColor(0x2A1C13),
            espressoHover: drColor(0x382818),
            roastedBean: drColor(0x3C2A1E),
            crater: drColor(0x4D3B31),
            crema: drColor(0xFFF7EE),
            warmWhite: drColor(0xF0E6D0),
            bone: drColor(0xEBE1D7),
            mocha: drColor(0x8B7355),
            craterDeep: drColor(0x3C2A21),
            asparagus: drColor(0x465945),
            rustic: drColor(0x480404),
            rose: drColor(0x480607),
            amber: drColor(0xE69A4C),
            amberHot: drColor(0xD2691E),
            amberMuted: drColor(0xC07A4A),
            gold: drColor(0xDAA520),
            brass: drColor(0xBFA162),
            scarlet: drColor(0xC44C4C),
            burntSienna: drColor(0xC75B39),
            teal: drColor(0x4CC4B4),
            magenta: drColor(0xC25F90),
            harvest: drColor(0xD4A040),
            olive: drColor(0x879A39),
            structural: drColor(0x4D3B31),
            sage: drColor(0x8AAC6B),
            slate: drColor(0x6E8FAD),
            mauve: drColor(0xAD7FA8)
            )
        case .houseBlend:
            return DarkRoastPalette(
            void_: drColor(0x241810),
            obsidian: drColor(0x2B1D14),
            darkCacao: drColor(0x322219),
            espresso: drColor(0x3B2A20),
            espressoHover: drColor(0x49362B),
            roastedBean: drColor(0x5A4538),
            crater: drColor(0x70594A),
            crema: drColor(0xFFF8F0),
            warmWhite: drColor(0xF4E8D8),
            bone: drColor(0xE9DCCF),
            mocha: drColor(0xBBA188),
            craterDeep: drColor(0x655043),
            asparagus: drColor(0x89B481),
            rustic: drColor(0x5C211C),
            rose: drColor(0x572039),
            amber: drColor(0xE9922E),
            amberHot: drColor(0xFF853D),
            amberMuted: drColor(0xDA9763),
            gold: drColor(0xD0A200),
            brass: drColor(0xBDA45D),
            scarlet: drColor(0xFE8175),
            burntSienna: drColor(0xFB864D),
            teal: drColor(0x2CB9AA),
            magenta: drColor(0xED85B8),
            harvest: drColor(0xD79B29),
            olive: drColor(0x9DAF48),
            structural: drColor(0xBCA18A),
            sage: drColor(0x79B56C),
            slate: drColor(0x6AACE2),
            mauve: drColor(0xD28DE2)
            )
        case .copperRoast:
            return DarkRoastPalette(
            void_: drColor(0x34251C),
            obsidian: drColor(0x3A2A20),
            darkCacao: drColor(0x402F24),
            espresso: drColor(0x47352A),
            espressoHover: drColor(0x523F33),
            roastedBean: drColor(0x634E40),
            crater: drColor(0x786151),
            crema: drColor(0xFFF9F4),
            warmWhite: drColor(0xF9EEE4),
            bone: drColor(0xF3E7DD),
            mocha: drColor(0xD0AE8E),
            craterDeep: drColor(0x6D584A),
            asparagus: drColor(0x89B47E),
            rustic: drColor(0x5B211B),
            rose: drColor(0x5D203D),
            amber: drColor(0xF5A33A),
            amberHot: drColor(0xFF8E3F),
            amberMuted: drColor(0xDE9656),
            gold: drColor(0xE4B20B),
            brass: drColor(0xC7A54A),
            scarlet: drColor(0xFF7D70),
            burntSienna: drColor(0xFB8349),
            teal: drColor(0x24C6B6),
            magenta: drColor(0xF47CBA),
            harvest: drColor(0xE0A225),
            olive: drColor(0xA1B73A),
            structural: drColor(0xC4A78E),
            sage: drColor(0x7DC45F),
            slate: drColor(0x5DB4E8),
            mauve: drColor(0xDB86D0)
            )
        case .coldBrew:
            return DarkRoastPalette(
            void_: drColor(0xE2DDD7),
            obsidian: drColor(0xD8CFC7),
            darkCacao: drColor(0xCDC2B7),
            espresso: drColor(0xC2B5A7),
            espressoHover: drColor(0xB1A291),
            roastedBean: drColor(0x96826C),
            crater: drColor(0x7C6449),
            crema: drColor(0x000000),
            warmWhite: drColor(0x030100),
            bone: drColor(0x100701),
            mocha: drColor(0x3B2301),
            craterDeep: drColor(0x867058),
            asparagus: drColor(0x162700),
            rustic: drColor(0xBD6062),
            rose: drColor(0xAF6297),
            amber: drColor(0x492B00),
            amberHot: drColor(0x632500),
            amberMuted: drColor(0x472400),
            gold: drColor(0x2D1F00),
            brass: drColor(0x342700),
            scarlet: drColor(0x940015),
            burntSienna: drColor(0x742400),
            teal: drColor(0x004444),
            magenta: drColor(0x640060),
            harvest: drColor(0x382500),
            olive: drColor(0x2B2B00),
            structural: drColor(0x7D6F5F),
            sage: drColor(0x0F3E02),
            slate: drColor(0x003F60),
            mauve: drColor(0x472077)
            )
        case .nitro:
            return DarkRoastPalette(
            void_: drColor(0xE1DDDA),
            obsidian: drColor(0xD5D0CB),
            darkCacao: drColor(0xCAC3BC),
            espresso: drColor(0xBFB5AE),
            espressoHover: drColor(0xADA299),
            roastedBean: drColor(0x918378),
            crater: drColor(0x766558),
            crema: drColor(0x000000),
            warmWhite: drColor(0x030100),
            bone: drColor(0x0E0804),
            mocha: drColor(0x362516),
            craterDeep: drColor(0x807165),
            asparagus: drColor(0x1A260C),
            rustic: drColor(0xA76F6E),
            rose: drColor(0x9E6F8E),
            amber: drColor(0x492B00),
            amberHot: drColor(0x632500),
            amberMuted: drColor(0x472400),
            gold: drColor(0x2D1F00),
            brass: drColor(0x342700),
            scarlet: drColor(0x7E312E),
            burntSienna: drColor(0x6B2D16),
            teal: drColor(0x004444),
            magenta: drColor(0x552552),
            harvest: drColor(0x382500),
            olive: drColor(0x2B2B00),
            structural: drColor(0x7A6F67),
            sage: drColor(0x213A1C),
            slate: drColor(0x0C3F5C),
            mauve: drColor(0x422F5F)
            )
        case .flashChilled:
            return DarkRoastPalette(
            void_: drColor(0xD4E1E3),
            obsidian: drColor(0xC2D5D9),
            darkCacao: drColor(0xB0C9CE),
            espresso: drColor(0x9EBEC4),
            espressoHover: drColor(0x87ACB3),
            roastedBean: drColor(0x5D9099),
            crater: drColor(0x30747F),
            crema: drColor(0x000000),
            warmWhite: drColor(0x000203),
            bone: drColor(0x000C0F),
            mocha: drColor(0x002F36),
            craterDeep: drColor(0x447F89),
            asparagus: drColor(0x162700),
            rustic: drColor(0xD14C55),
            rose: drColor(0xBE509F),
            amber: drColor(0x492B00),
            amberHot: drColor(0x632500),
            amberMuted: drColor(0x472400),
            gold: drColor(0x2D1F00),
            brass: drColor(0x342700),
            scarlet: drColor(0x940015),
            burntSienna: drColor(0x742400),
            teal: drColor(0x004444),
            magenta: drColor(0x640060),
            harvest: drColor(0x382500),
            olive: drColor(0x2B2B00),
            structural: drColor(0x54797F),
            sage: drColor(0x0D3E00),
            slate: drColor(0x003F60),
            mauve: drColor(0x4D008A)
            )
        case .cascara:
            return DarkRoastPalette(
            void_: drColor(0xE5DBDA),
            obsidian: drColor(0xDCCDCB),
            darkCacao: drColor(0xD2BFBD),
            espresso: drColor(0xC9B1AF),
            espressoHover: drColor(0xB99D9A),
            roastedBean: drColor(0x9F7C79),
            crater: drColor(0x865D59),
            crema: drColor(0x010000),
            warmWhite: drColor(0x050101),
            bone: drColor(0x130504),
            mocha: drColor(0x441A18),
            craterDeep: drColor(0x906966),
            asparagus: drColor(0x162700),
            rustic: drColor(0xC25C5F),
            rose: drColor(0xB35E99),
            amber: drColor(0x492B00),
            amberHot: drColor(0x632500),
            amberMuted: drColor(0x472400),
            gold: drColor(0x2D1F00),
            brass: drColor(0x342700),
            scarlet: drColor(0x940015),
            burntSienna: drColor(0x742400),
            teal: drColor(0x004444),
            magenta: drColor(0x640060),
            harvest: drColor(0x382500),
            olive: drColor(0x2B2B00),
            structural: drColor(0x846A68),
            sage: drColor(0x0D3E00),
            slate: drColor(0x003F60),
            mauve: drColor(0x491A7C)
            )
        }
    }
}

public struct DarkRoastPalette {
    public let void_: Color
    public let obsidian: Color
    public let darkCacao: Color
    public let espresso: Color
    public let espressoHover: Color
    public let roastedBean: Color
    public let crater: Color
    public let crema: Color
    public let warmWhite: Color
    public let bone: Color
    public let mocha: Color
    public let craterDeep: Color
    public let asparagus: Color
    public let rustic: Color
    public let rose: Color
    public let amber: Color
    public let amberHot: Color
    public let amberMuted: Color
    public let gold: Color
    public let brass: Color
    public let scarlet: Color
    public let burntSienna: Color
    public let teal: Color
    public let magenta: Color
    public let harvest: Color
    public let olive: Color
    public let structural: Color
    public let sage: Color
    public let slate: Color
    public let mauve: Color
}

private struct DarkRoastPaletteKey: EnvironmentKey {
    static let defaultValue = DarkRoastThemeVariant.blackLabel.palette
}

public extension EnvironmentValues {
    /// The selected additive Dark Roast palette. This does not replace the
    /// legacy darkRoastTheme value from EnhancedDarkRoastTheme.
    var darkRoastPalette: DarkRoastPalette {
        get { self[DarkRoastPaletteKey.self] }
        set { self[DarkRoastPaletteKey.self] = newValue }
    }
}

public extension View {
    /// Select a Dark Roast family palette for this view hierarchy.
    func darkRoastPalette(_ variant: DarkRoastThemeVariant) -> some View {
        environment(\.darkRoastPalette, variant.palette)
    }
}

private func drColor(_ hex: UInt32) -> Color {
    Color(
        .sRGB,
        red: Double((hex >> 16) & 0xFF) / 255,
        green: Double((hex >> 8) & 0xFF) / 255,
        blue: Double(hex & 0xFF) / 255,
        opacity: 1
    )
}
